---
- name: Actualizar Servidores
  hosts: all
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
      register: update_result

    - name: Registrar tiempo de instalaci贸n y reinicio
      win_shell: |
        $Now = Get-Date
        $ElapsedTime = $Now - [DateTime]{{ update_result.start }}
        Add-Content -Path "C:\update_duration.log" -Value "Inicio de actualizaci贸n: $Now"
        Add-Content -Path "C:\update_duration.log" -Value "Duraci贸n de la actualizaci贸n: $ElapsedTime"
      when: update_result.reboot_required == true
