---
- name: Validar actualizaciones pendientes en sistemas Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Verificar actualizaciones pendientes
      win_updates:
        state: pending
      register: pending_updates

    - name: Mostrar listado de actualizaciones pendientes
      debug:
        var: pending_updates

