---
- name: Crear archivo de texto con hora y fecha en disco C
  hosts: windows_servers
  tasks:
    - name: Obtener hora y fecha del servidor
      win_shell: Get-Date -Format "yyyy-MM-dd HH-mm-ss"
      register: server_datetime

    - name: Crear archivo de texto con hora y fecha
      win_shell: |
        $Content = "{{ server_datetime.stdout }}"
        Set-Content -Path "C:\archivo_con_fecha.txt" -Value $Content


