---
- name: Actualizar Servidores
  hosts: all
  become: true
  become_method: runas
  become_user: administrator  # Replace with the appropriate username
  tasks:
    - name: Descargar e instalar actualizaciones de Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: true
      tags:
        - updates
    - name: Verificar si quedan actualizaciones pendientes después del reinicio
      win_updates:
        state: searched
      register: pending_updates
    - name: Mostrar listado de actualizaciones pendientes
      debug:
        var: pending_updates.updates
      tags:
        - updates

