---
- name: Generar archivo con hora en el escritorio
  hosts: all
  become: true
  become_method: runas
  become_user: administrator  # Reemplaza con el nombre de usuario apropiado
  gather_facts: no
  tasks:
    - name: Obtener la hora actual
      ansible.builtin.win_shell: powershell Get-Date -Format "yyyyMMdd_HHmmss"
      register: current_time

    - name: Crear archivo en el escritorio con la hora
      ansible.builtin.win_shell: |
        $current_time = "{{ current_time.stdout }}"
        $desktop_path = [System.IO.Path]::Combine($env:USERPROFILE, 'Desktop')
        $file_path = Join-Path $desktop_path "archivo_{{ current_time }}.txt"
        Set-Content -Path $file_path -Value "Contenido del archivo con la hora: $current_time"
