---
- name: Descargar e instalar actualizaciones en Windows
  hosts: tu_host_windows
  gather_facts: no
  tasks:
    - name: Descargar actualizaciones
      win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed
      register: update_result
 
    - name: Mostrar detalles de las actualizaciones descargadas e instaladas
      debug:
        var: update_result
