---
- name: Crear archivo TXT en disco C
  hosts: all
  become: true
  become_method: runas
  become_user: vdadm  # Reemplaza con el nombre de usuario apropiado
  gather_facts: no
  tasks:
    - name: Crear archivo en disco C
      ansible.builtin.win_shell: |
        $content = "Contenido del archivo TXT"
        $file_path = "C:\archivo.txt"
        Set-Content -Path $file_path -Value $content

