---
- name: Update Windows system and create log file
  hosts: all
  become: yes
  become_method: runas

  tasks:
    - name: Update system
      win_updates:
        category_names:
          - SecurityUpdates
          - UpdateRollups
          - CriticalUpdates
        state: installed

    - name: Create log file
      win_shell: |
        $logFilePath = "C:update_log.txt"
        Get-HotFix | Format-Table -Property Description, InstalledOn | Out-File -FilePath $logFilePath

    - name: Display completion message
      debug:
        msg: "System updated, and log created at C:update_log.txt"

