---
- name: Create log file in the root of C
  hosts: all
  become: true
  become_method: runas
  become_user: vdadm 
  gather_facts: false

  tasks:
    - name: Check for available updates
      win_updates:
        category_names:
          - SecurityUpdates
        state: searched
      register: win_updates_result

    - name: Install security updates
      win_updates:
        category_names:
          - SecurityUpdates
        state: installed
      when: win_updates_result.updates | length > 0

    - name: Create log file indicating pending or installed updates
      win_shell: |
        $logFilePath = "C:\update_status_log.txt"
        
        if (win_updates_result.updates | length > 0) {
          "Pending updates found. Please run 'win_updates' task to install updates." | Out-File -FilePath $logFilePath -Encoding UTF8
        } else {
          "No pending updates. Security updates are up to date." | Out-File -FilePath $logFilePath -Encoding UTF8
        }
      when: win_updates_result.updates | length > 0
