---
- name: Create log file in the root of C
  hosts: all
  become: true
  become_method: runas
  become_user: vdadm 
  gather_facts: false

  tasks:
    - name: Check for available updates
      win_updates:
        category_names:
          - SecurityUpdates
        state: searched
      register: win_updates_result

    - name: Install security updates
      win_updates:
        category_names:
          - SecurityUpdates
        state: installed
      when: win_updates_result.updates | length > 0

    - name: Create log file in the root of C
      win_shell: |
        $logFilePath = "C:\security_update_log.txt"
        "Installed security updates: {{ win_updates_result.updates | map(attribute='title') | join(', ') }}" | Out-File -FilePath $logFilePath -Encoding UTF8
      when: win_updates_result.updates | length > 0

        "Installed security updates: {{ win_updates_result.updates | map(attribute='title') | join(', ') }}" | Out-File -FilePath $logFilePath
      when: win_updates_result.updates | length > 0
